### ISSUE TITLE
Need help setting-up: nothing being tracked in redis

### ISSUE THREAD

**Issue by vinay-eaccent** [Springest/rack-request_replication#5]
Hello, thanks for this interesting gem!

I'm trying to setup this gem for my Rails application running on nginx + passenger and notice that nothing is being recorded in redis. I'm guessing that's the reason the replication target server is unable to verify requests. I've enabled the middleware exactly as described in the README.

I turned-on redis debug logs and noticed that no keys are being added for CSRF tokens or sessions. The logger referenced in forwarder.rb is logging to neither nginx or application logs.

Please could you suggest how I can go about detecting the real problem here?

**Comment by timflapper** [comment]
@vinay-eaccent, they only thing I can think of is debugging it locally and checking what's happening. You can always just clone the code locally and use the local path in your Gemfile.

**Comment by vinay-eaccent** [comment]
Thanks @timflapper! let me give that a shot.
